/**
 * Query guidance resource for MCP clients and LLMs
 */

export const queryGuidanceResource = {
  uri: 'terminal49://docs/mcp-query-guidance',
  name: 'MCP Query Guidance',
  description:
    'Structured playbooks for common container logistics questions. Helps clients map user intent to tools and output shape.',
  mimeType: 'text/markdown',
};

export function readQueryGuidanceResource(): string {
  return [
    '# Terminal49 MCP Query Guidance',
    '',
    'Use this document to map user questions to the right tool sequence, plus output expectations.',
    '',
    '## Intent → Tool Mapping',
    '',
    '### 1) Single container status / pickup readiness',
    '- Question examples:',
    '  - "Is container [X] ready for pickup?"',
    '  - "What is the pickup status?"',
    '  - "Is container ready for pickup yet?"',
    '- Primary tool: get_container',
    '- Input: use container UUID from search',
    '- Follow-up: call get_container with include: ["shipment","pod_terminal"]',
    '- If uncertain state: call get_container_transport_events',
    '',
    '### 2) Current position / what is container doing',
    '- Question examples:',
    '  - "What is container [X] doing?"',
    '  - "What\'s going on with container [X]?"',
    '  - "Where is it?"',
    '- Primary tool: get_container_transport_events',
    '- Input: include container UUID',
    '- Output expectation: timeline + event_categories + milestones',
    '',
    '### 3) Discharge / pickup availability',
    '- Question examples:',
    '  - "Which containers have been discharged but not picked up?"',
    '  - "Any holds on [X]?"',
    '- Primary tools: list_containers or list_shipments then get_container',
    '- Supported list filters: status, port, carrier, updated_after (no has_hold filter exists).',
    '- "Discharged but not picked up" is derived client-side: keep rows where podDischargedAt is set and podFullOutAt is empty. Hold state comes from the holdsAtPodTerminal field on each row, not a filter.',
    '',
    '### 4) Arrival / ETAs / delays',
    '- Question examples:',
    '  - "When is [vessel] arriving?"',
    '  - "What is arriving at LA this week?"',
    '  - "When should I get to LA this week?"',
    '- Primary tool: search_container then get_container for specific container',
    '- Secondary: get_container_transport_events for delay context',
    '',
    '### 5) Shipment-level discovery',
    '- Question examples:',
    '  - "Show me everything on BL [X]"',
    '  - "Show shipment [X] and all containers"',
    '- Primary tool: search_container or get_shipment_details',
    '- Output expectation: shipment-level identifiers and container list',
    '',
    '### 6) Demurrage monitoring',
    '- Question examples:',
    '  - "Do I have any containers with demurrage risk?"',
    '  - "Which containers are at risk of LFD?"',
    '- Primary tool: list_containers plus get_container',
    '- Supported list filters: status, port, carrier, updated_after. The list endpoint has no server-side sort; order rows client-side by the pickupLfd field returned on each container, and surface holdsAtPodTerminal alongside it.',
    '',
    '## Output Formatting Guidance',
    '',
    '- Always return concise status first.',
    '- Keep containers grouped by outcome state.',
    '- When the response includes holdsAtPodTerminal entries, call out those explicitly and escalate urgency.',
    '- When dates are missing, explain that latest feed is partial and suggest get_container_transport_events for timeline context.',
    '- Always suggest 1-2 concrete next checks when data is incomplete.',
    '',
    '## Recommended follow-up tool calls',
    '',
    '1. Use search_container for any unrecognized identifier.',
    '2. Resolve to a container UUID.',
    '3. Use get_container for baseline state.',
    '4. If timeline needed, follow with get_container_transport_events.',
    '',
  ].join('\n');
}
