/**
 * Query guidance resource for MCP clients and LLMs
 */

export const queryGuidanceResource = {
  uri: 'terminal49://docs/mcp-query-guidance',
  name: 'MCP Query Guidance',
  description:
    'Structured playbooks for common container logistics questions. Helps clients map user intent to tools and output shape.',
  mimeType: 'text/markdown',
};

export function readQueryGuidanceResource(): string {
  return [
    '# Terminal49 MCP Query Guidance',
    '',
    'Use this document to map user questions to the right tool sequence, plus output expectations.',
    '',
    '## Account-wide analytics with query',
    '- query accepts one PostgreSQL SELECT over account-scoped assistant_* views. It returns at most 500 rows; use COUNT(*) for a true total.',
    '- assistant_containers has one row per container and is the usual starting point. Useful columns include container_number, container_url, shipment_number, shipment_url, bl_number, booking_number, current_status, pod_name, pod_code, pod_time_zone, pod_eta_at, pod_arrived_at, pod_discharged_at, picked_up_at, pickup_lfd, pod_terminal_holds, pod_terminal_fees, and shipping_line_name.',
    '- Other views: assistant_transport_events, assistant_pod_terminal_updates, assistant_pod_eta_changes, assistant_tracking_requests, assistant_custom_fields, assistant_custom_field_definitions, assistant_documents, assistant_links.',
    "- Count example: SELECT COUNT(*) AS container_count FROM assistant_containers WHERE pod_name ILIKE '%Los Angeles%' AND pod_eta_at >= NOW() AND pod_eta_at < NOW() + INTERVAL '7 days';",
    "- Detail example: SELECT container_number, container_url, shipment_number, pod_eta_at, pod_time_zone FROM assistant_containers WHERE pod_name ILIKE '%Los Angeles%' AND pod_eta_at >= NOW() AND pod_eta_at < NOW() + INTERVAL '7 days' ORDER BY pod_eta_at LIMIT 50;",
    '- If a query fails, fix the SQL and retry. Do not invent a count from a paginated list.',
    '',
    '## Intent → Tool Mapping',
    '',
    '### 1) Single container status / pickup readiness',
    '- Question examples:',
    '  - "Is container [X] ready for pickup?"',
    '  - "What is the pickup status?"',
    '  - "Is container ready for pickup yet?"',
    '- Primary tool: get_container',
    '- Input: use container UUID from search',
    '- Follow-up: call get_container with include: ["shipment","pod_terminal"]',
    '- If uncertain state: call get_container_transport_events',
    '',
    '### 2) Current position / what is container doing',
    '- Question examples:',
    '  - "What is container [X] doing?"',
    '  - "What\'s going on with container [X]?"',
    '  - "Where is it?"',
    '- Primary tool: get_container_transport_events',
    '- Input: include container UUID',
    '- Output expectation: timeline + event_categories + milestones',
    '',
    '### 3) Discharge / pickup availability',
    '- Question examples:',
    '  - "Which containers have been discharged but not picked up?"',
    '  - "Any holds on [X]?"',
    '- Primary tool: query against assistant_containers',
    '- Use SQL filters for a complete account-wide worklist; list_containers has no server-side operational filters.',
    '- "Discharged but not picked up" is derived client-side from returned rows: keep rows where podDischargedAt is set and podFullOutAt is empty. Hold state comes from holdsAtPodTerminal, not a filter.',
    '',
    '### 4) Arrival / ETAs / delays',
    '- Question examples:',
    '  - "When is [vessel] arriving?"',
    '  - "What is arriving at LA this week?"',
    '  - "When should I get to LA this week?"',
    '- Primary tool: query for a port-wide worklist; search_container then get_container for a specific container',
    '- Secondary: get_container_transport_events for delay context',
    '',
    '### 5) Shipment-level discovery',
    '- Question examples:',
    '  - "Show me everything on BL [X]"',
    '  - "Show shipment [X] and all containers"',
    '- Primary tool: search_container or get_shipment_details',
    '- Output expectation: shipment-level identifiers and container list',
    '',
    '### 6) Demurrage monitoring',
    '- Question examples:',
    '  - "Do I have any containers with demurrage risk?"',
    '  - "Which containers are at risk of LFD?"',
    '- Primary tool: query against assistant_containers',
    '- list_containers has no server-side filter or sort. Order each returned page client-side by pickupLfd and surface holdsAtPodTerminal, but do not claim the page represents every at-risk container in the account.',
    '',
    '### 7) Shipment list filtering',
    '- list_shipments supports shipment number and tracking_stopped filters.',
    '- Status, port, carrier, and updated-time filters are not supported by the API and must not be presented as applied.',
    '',
    '## Output Formatting Guidance',
    '',
    '- Always return concise status first.',
    '- Keep containers grouped by outcome state.',
    '- When the response includes holdsAtPodTerminal entries, call out those explicitly and escalate urgency.',
    '- When dates are missing, explain that latest feed is partial and suggest get_container_transport_events for timeline context.',
    '- Always suggest 1-2 concrete next checks when data is incomplete.',
    '',
    '## Recommended follow-up tool calls',
    '',
    '1. Use search_container for any unrecognized identifier.',
    '2. Resolve to a container UUID.',
    '3. Use get_container for baseline state.',
    '4. If timeline needed, follow with get_container_transport_events.',
    '',
  ].join('\n');
}
