/**
 * Query guidance resource for MCP clients and LLMs
 */

export const queryGuidanceResource = {
  uri: 'terminal49://docs/mcp-query-guidance',
  name: 'MCP Query Guidance',
  description:
    'Structured playbooks for common container logistics questions. Helps clients map user intent to tools and output shape.',
  mimeType: 'text/markdown',
};

export function readQueryGuidanceResource(): string {
  return [
    '# Terminal49 MCP Query Guidance',
    '',
    'Use this document to map user questions to the right tool sequence, plus output expectations.',
    '',
    '## Intent → Tool Mapping',
    '',
    '### 1) Single container status / pickup readiness',
    '- Question examples:',
    '  - "Is container [X] ready for pickup?"',
    '  - "What is the pickup status?"',
    '  - "Is container ready for pickup yet?"',
    '- Primary tool: get_container',
    '- Input: use container UUID from search',
    '- Follow-up: call get_container with include: ["shipment","pod_terminal"]',
    '- If uncertain state: call get_container_transport_events',
    '',
    '### 2) Current position / what is container doing',
    '- Question examples:',
    '  - "What is container [X] doing?"',
    '  - "What\'s going on with container [X]?"',
    '  - "Where is it?"',
    '- Primary tool: get_container_transport_events',
    '- Input: include container UUID',
    '- Output expectation: timeline + event_categories + milestones',
    '',
    '### 3) Discharge / pickup availability',
    '- Question examples:',
    '  - "Which containers have been discharged but not picked up?"',
    '  - "Any holds on [X]?"',
    '- Primary tools: list_containers or list_shipments then get_container',
    '- list_containers supports operational filters. For discharged but not picked up, use advanced_filters: { pod_discharged_at: "@exists", picked_up_at: "@not_exists" }. For terminal holds, use has_holds: true.',
    '- Verify returned milestones before describing pickup readiness. Missing terminal hold data is different from an explicitly empty holds array.',
    '',
    '### 4) Arrival / ETAs / delays',
    '- Question examples:',
    '  - "When is [vessel] arriving?"',
    '  - "What is arriving at LA this week?"',
    '  - "When should I get to LA this week?"',
    '- Primary tool: search_container then get_container for a specific container. For fleet arrivals, use list_shipments with pod_code and pod_arrival date bounds, or list_containers with arrival.',
    '- Secondary: get_container_transport_events for delay context',
    '',
    '### 5) Shipment-level discovery',
    '- Question examples:',
    '  - "Show me everything on BL [X]"',
    '  - "Show shipment [X] and all containers"',
    '- Primary tool: search_container or get_shipment_details',
    '- Output expectation: shipment-level identifiers and container list',
    '',
    '### 6) Demurrage monitoring',
    '- Question examples:',
    '  - "Do I have any containers with demurrage risk?"',
    '  - "Which containers are at risk of LFD?"',
    '- Primary tool: list_containers plus get_container',
    '- Use list_containers with pickup_lfd date bounds, actively_tracked: true, and sort: "pickup_lfd". Use has_fees: true for reported terminal fees. Missing fee data does not satisfy has_fees: false.',
    '',
    '### 7) Shipment list filtering',
    '- list_shipments supports common filters directly and all confirmed shipment filters in typed advanced_filters. Use voyage_status for arrived/on_ship; it is not a container lifecycle status.',
    '- list_containers supports current_status, pod_code, shipping_line_scac, holds, fees, dates, tags, and advanced_filters. Resolve carrier SCAC with get_supported_shipping_lines. Obtain account-visible IDs from authorized records; never invent UUIDs.',
    '- Supply each filter at the top level or in advanced_filters, never both. Sort and pagination belong at the top level.',
    '- Container pod_eta_at, pod_ata_at, and custom_fields filters are unavailable. Reading custom-field values with detail tools is separate.',
    '',
    '## Filter values and pagination',
    '',
    '- Follow the typed tool schema for finite values, operators, and per-filter AND/OR behavior. One-way selectors accept true only; omit them to disable them.',
    '- Date-only filters compare stored calendar dates. Shipment created_at and pod_eta_changed_at require offset-bearing timestamps. For a local port day, query overlapping stored dates and refine returned timestamps with the port timezone.',
    '- Every list call retrieves one page, capped at 25 rows. _metadata.applied_filters records canonical filters, and _metadata.has_more is true, false, or null when paging is unknown.',
    '- When more pages remain, keep the same filters, sort, and includes and request _metadata.next_page or the page number from links.next. Never describe one page as an entire worklist.',
    '- A last page does not establish that earlier pages were retrieved. Distinguish retrieved count from API meta.total and account for records changing between calls.',
    '- Full reference: https://docs.terminal49.com/api-docs/api-reference/list-filters',
    '',
    '## Output Formatting Guidance',
    '',
    '- Always return concise status first.',
    '- Keep containers grouped by outcome state.',
    '- When the response includes holdsAtPodTerminal entries, call out those explicitly and escalate urgency.',
    '- When dates are missing, explain that latest feed is partial and suggest get_container_transport_events for timeline context.',
    '- Always suggest 1-2 concrete next checks when data is incomplete.',
    '',
    '## Recommended follow-up tool calls',
    '',
    '1. Use search_container for any unrecognized identifier.',
    '2. Resolve to a container UUID.',
    '3. Use get_container for baseline state.',
    '4. If timeline needed, follow with get_container_transport_events.',
    '',
  ].join('\n');
}
