name: Deploy Postman Collection

on:
  workflow_run:
    workflows: ["Generate Postman Collection"]
    types:
      - completed
    # branches:
    #   - main # Directly filter for master branch here

jobs:
  deploy-to-postman:
    runs-on: ubuntu-latest
    # Simpler conditional check
    if: github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Debug Workflow Run Event
        run: |
          echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow commit: ${{ github.event.workflow_run.head_sha }}"
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install jq # For JSON manipulation
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update Postman Collection via API
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_COLLECTION_UID: 26830108-7c90c1cf-358d-44b6-9e64-0647c12b555b # Your collection UID
          # Assuming the file is checked out or downloaded to this name
          COLLECTION_FILE: Terminal49-API.postman_collection.json
        run: |
          echo "Deploy workflow triggered by completion of Generate workflow run ID ${{ github.event.workflow_run.id }} on commit ${{ github.event.workflow_run.head_sha }} for branch ${{ github.event.workflow_run.head_branch }}"

          # Check if API key is set
          if [ -z "$POSTMAN_API_KEY" ]; then
            echo "Error: POSTMAN_API_KEY secret is not set."
            exit 1
          fi

          # Check if collection file exists (critical after checkout)
          if [ ! -f "$COLLECTION_FILE" ]; then
            echo "Error: Collection file '$COLLECTION_FILE' not found at commit ${{ github.event.workflow_run.head_sha }}. Was it generated and committed by the previous workflow?"
            # It's possible the generate workflow found no changes and didn't commit/push.
            # If that's okay, you might exit cleanly here instead of erroring.
            # echo "Skipping deployment as collection file was not found (likely no changes were generated)."
            # exit 0
            exit 1 # Exiting with error as current setup expects a commit if triggered
          fi

          # Construct the JSON payload using jq
          JSON_PAYLOAD=$(jq --null-input --rawfile collection "$COLLECTION_FILE" '{ "collection": ($collection | fromjson) }')

          if [ $? -ne 0 ]; then
            echo "Error: jq failed to process $COLLECTION_FILE. Is it valid JSON?"
            exit 1
          fi

          # Make the API call
          curl --location --fail --request PUT "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_UID" \
          --header 'Content-Type: application/json' \
          --header "X-Api-Key: $POSTMAN_API_KEY" \
          --data "$JSON_PAYLOAD"

          if [ $? -eq 0 ]; then
            echo "Postman collection update request sent successfully."
          else
            echo "Error: Failed to update Postman collection via API. Check curl output above."
            exit 1
          fi
